### ISSUE TITLE
Issues retrieving value

### ISSUE THREAD

**Issue by fahlout** [owowagency/KeychainStored#1]
I have 2 String properties that I'm using your property wrapper for to store in the keychain. It does seem to store them just fine but when I retrieve them I seem to sometimes get back the wrong value. It happens in particular after quitting the app and restarting where I will get the same value for both properties.

Are each of my properties supposed to be keyed uniquely and how are the keys generated. I couldn't figure out how that is implemented skimming through your code.

**Comment by fahlout** [comment]
Follow up:
Is the service supposed to be my key instead of the bundle identifier? Once I changed the service to be a unique value for each of my properties the issue seems to not occur anymore. Does this property wrapper access the keychain of the app defined by the bundle identifier by default?

**Comment by gerchicov-bp** [comment]
@fahlout it seems it doesn't work properly. I store a value and I'm able to retrieve it. But it disappears on app restart

**Comment by Obbut** [comment]
If this happens again, please share example code that triggers this and I'm happy to help. In our apps so far it's working fine.
