### ISSUE TITLE
Xcode 12 iOS deployment target warning

### ISSUE THREAD

**Issue by rainypixels** [owowagency/KeychainStored#2]
Compiling in Xcode 12 throws this warning (project compiles successfully):

> The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

Presumably the version needs to be bumped to `.v9` here? https://github.com/owowagency/KeychainStored/blob/20b75d23fd1f19565c3dfe477b2ebf5c194db5f7/Package.swift#L8

**Comment by Obbut** [comment]
Fixed in fb93df5ea77cd9836720473813e23008abfa4d21 – I will tag a new version soon
Thanks!
